### ISSUE TITLE
Broken in new source engine update.

### ISSUE THREAD

**Issue by blankrofl** [sk89q/playx#31]
[addons\playx\lua\entities\gmod_playx\cl_init.lua:504] attempt to call method 'GetHTMLMaterial' (a nil value)

Appears to be the culprit. I attempted to fix it myself but I don't know much lua, and wasn't sure why getHTMLMaterial() is returning nil.

Sound does not play with this issue.

**Comment by NickoftheDead** [comment]
I'm having the same problem.

**Comment by sk89q** [comment]
Apparently it has to be fixed in a Gmod update or something.

**Comment by blankrofl** [comment]
Any way a temporary fix could be made? Or is this a non fixable thing. GM13 had an update involving a new HTML render system, but this doesn't affect normal gmod.

**Comment by sk89q** [comment]
So this only affects Gmod 13 and not the main branch? I'll see if I can look into it, but I read somewhere that it may be a temporary problem.

**Comment by blankrofl** [comment]
No it DOES affect the main branch. But it was a coincidence that at about the time PlayX broke, GM13 had an update that involved an HTML render engine. Just stating if it had any relevance.

**Comment by blankrofl** [comment]
http://garrysmod.com/post/26915045409/gmod-update-137

Supposedly it is fixed now.

**Comment by blankrofl** [comment]
Just tested it out with the beta svn, it is not fixed, but no longer gives errors.

**Comment by pommy159** [comment]
I just get the error "Browser Message: Uncaught TypeError: Cannot call method 'getAttribute' of null - (null):63"

**Comment by Titanic4** [comment]
I got the same error too as you, Pommy

**Comment by nathan847** [comment]
same ^^^

**Comment by pommy159** [comment]
Any idea of when this is going to get fixed? Because people love Playx on my server.

**Comment by pommy159** [comment]
I was able to play a YouTube video with the 'non browse able webpage' setting and this worked, i go to try the YouTube setting and it says to download flash player other versions, i will be downloading it now to see if this makes a difference.

**Comment by pommy159** [comment]
Well i played a non brows able webpage, and after that, a friend used the !ytplay command and the videos seemed to work somehow.

**Comment by pommy159** [comment]
You have to 'wake it up' with a non browsable webpage' and then the !ytplay commands work, but the navigator still doesn't work (not saying that's not a bad thing)
