### ISSUE TITLE
Another broken update

### ISSUE THREAD

**Issue by matthewshirley** [sk89q/playx#32]
An update with Garrys Mod has caused issues with loading videos. No suitable fix is around. To recreate, simply try and play a video.

`PlayX DEBUG: Providers list received
PlayX DEBUG: JW URL set
PlayX DEBUG: Host URL set
Redownloading all lightmaps
PlayX: Beginning media nCgQDjiotG0 with handler YouTubePopup, start at 0s
PlayX: Metadata function available via provider YouTube
PlayX: Playing nCgQDjiotG0 using handler YouTubePopup
PlayX DEBUG: Page loaded, preparing to inject
Browser Message: Uncaught TypeError: Cannot call method 'getAttribute' of null - (null):63
PlayX: Received metadata via provider YouTube
PlayX DEBUG: Metadata received`

**Comment by sk89q** [comment]
I'd like to fix PlayX but I am currently a bit short on time and it may be a few more weeks unless someone wants to hack at the code in the repository.
