### ISSUE TITLE
Unable to see videos on mac

### ISSUE THREAD

**Issue by MTG141** [sk89q/playx#41]
on mac i only get the audio but the screen is just black, plz fix

**Comment by Abwort** [comment]
I Don't know, i just feel left out. my friends are making fun of my for not having playX 2.6. I feel left out. Help Soon Any Admin!!!

**Comment by Bryantdl7** [comment]
Its not Mac compatible, use bootcamp and put windows 7 on your mac dude.

**Comment by sk89q** [comment]
This issue is a year old, and I'm not even the maintainer of PlayX anymore.
